set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR /opt/avr-gcc/bin/avr)
set(CMAKE_C_COMPILER /opt/avr-gcc/bin/avr-gcc)
set(CMAKE_CXX_COMPILER /opt/avr-gcc/bin/avr-g++)
set(CMAKE_ASM_COMPILER /opt/avr-gcc/bin/avr-gcc)
set(CMAKE_C_COMPILER_TARGET /opt/avr-gcc/bin/avr)
set(CMAKE_CXX_COMPILER_TARGET /opt/avr-gcc/bin/avr)
set(CMAKE_ASM_COMPILER_TARGET /opt/avr-gcc/bin/avr)
add_compile_options(-mmcu=${MCU})
add_compile_definitions(F_CPU=${F_CPU})
add_link_options(-mmcu=${MCU})