set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)
set(CMAKE_C_COMPILER avr-gcc)
set(CMAKE_CXX_COMPILER avr-g++)
set(CMAKE_ASM_COMPILER avr-gcc)
set(CMAKE_C_COMPILER_TARGET avr)
set(CMAKE_CXX_COMPILER_TARGET avr)
set(CMAKE_ASM_COMPILER_TARGET avr)
add_compile_options(-mmcu=${MCU})
add_compile_definitions(F_CPU=${F_CPU})
add_link_options(-mmcu=${MCU})