name: Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        board: [lafortuna]
    runs-on: ubuntu-latest
    steps:
      # - name: install build toolchain
      #   uses: daaku/gh-action-apt-install@v4
      #   with:
      #     packages: make gcc-avr avr-libc
      - name: install build toolchain
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
          sudo apt install --no-install-recommends make avr-libc srecord
      
      - name: cache prebuilt avr-gcc
        id: cache-compiler
        uses: actions/cache@v4
        with: 
          path: ${{github.workspace}}/opt/modm-avr-gcc
          key: ${{ runner.os }}-avr-gcc
      - name: download prebuilt avr-gcc
        if: steps.cache-compiler.outputs.cache-hit != 'true'
        run: | 
          wget https://github.com/modm-io/avr-gcc/releases/download/v14.2.0/modm-avr-gcc.tar.bz2
          mkdir opt
          tar xf modm-avr-gcc.tar.bz2 --directory ${{github.workspace}}/opt
      - name: enable prebuilt avr-gcc
        run: |
          sudo cp -r ${{github.workspace}}/opt/modm-avr-gcc/* /usr/
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build_${{matrix.board}}
          cd build_${{matrix.board}}
          cmake -DBOARD=${{matrix.board}} ..
          cmake --build . -v
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-${{matrix.board}}
          path: |
            build_${{matrix.board}}/**/*.hex
            build_${{matrix.board}}/**/*.eep
            build_${{matrix.board}}/**/*.bin
            build_${{matrix.board}}/**/*.a
            build_${{matrix.board}}/**/*.elf


          