name: Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        board: [lafortuna ilmatto]
    runs-on: ubuntu-latest
    steps:
      - name: install build toolchain
        uses: daaku/gh-action-apt-install@v4
        with:
          packages: make gcc-avr avr-libc
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build
        run:
          make BOARD=${{matrix.board}} BLD_DIR=build_${{matrix.board}} all
          