name: Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        board: [lafortuna, ilmatto]
    runs-on: ubuntu-latest
    steps:
      # - name: install build toolchain
      #   uses: daaku/gh-action-apt-install@v4
      #   with:
      #     packages: make gcc-avr avr-libc
      - name: install build toolchain
        run: sudo apt install make gcc-avr avr-libc srecord
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build
        run:
          make BOARD=${{matrix.board}} BLD_DIR=build_${{matrix.board}} all
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-${{matrix.board}}
          path: |
            build_${{matrix.board}}/**.hex
            build_${{matrix.board}}/**.eep
            build_${{matrix.board}}/**.bin
            build_${{matrix.board}}/**.a
            build_${{matrix.board}}/**.elf


          