name: Build
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        board: [lafortuna]
    runs-on: ubuntu-latest
    steps:
      # - name: install build toolchain
      #   uses: daaku/gh-action-apt-install@v4
      #   with:
      #     packages: make gcc-avr avr-libc
      - name: install build toolchain
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate >/dev/null
          sudo dpkg-reconfigure man-db
          sudo apt install --no-install-recommends make avr-libc srecord
      
      - name: cache prebuilt avr-gcc
        id: cache-compiler
        uses: actions/cache@v4
        with: 
          path: ${{github.workspace}}/gcc
          key: ${{ runner.os }}-avr-gcc
      - name: clone and build avr-gcc
        if: steps.cache-compiler.outputs.cache-hit != 'true'
        run: | 
          git clone https://github.com/gcc-mirror/gcc.git ${{github.workspace}}/gcc
          pushd ${{github.workspace}}/gcc
          git checkout releases/gcc-14.2.0
          mkdir build
          cd build
          ../configure --prefix=/usr --target=avr --enable-languages=c,c++ --disable-nls --disable-libssp --with-dwarf2
          make -j$(nproc)
          popd

          
      - name: enable avr-gcc
        run: |
          pushd ${{github.workspace}}/gcc/build
          sudo make install
          # sudo cp -r ${{github.workspace}}/opt/avr-gcc/* /usr/
          # echo "${{github.workspace}}/opt/avr-gcc/bin" >> $GITHUB_PATH
          popd
      - name: checkout repo
        uses: actions/checkout@v2
      # - name: build
      #   run: |
      #     mkdir build_${{matrix.board}}
      #     cd build_${{matrix.board}}
      #     cmake -DBOARD=${{matrix.board}} ..
      #     cmake --build . -v
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-${{matrix.board}}
          path: |
            build_${{matrix.board}}/**/*.hex
            build_${{matrix.board}}/**/*.eep
            build_${{matrix.board}}/**/*.bin
            build_${{matrix.board}}/**/*.a
            build_${{matrix.board}}/**/*.elf


          